{
  "schema_version": 1,
  "profiles": [
    {
      "feature": "ipmctl",
      "id": "trixie-v03.00.00.0538",
      "repository_url": "https://github.com/intel/ipmctl.git",
      "release": "v03.00.00.0538",
      "commit": "a71f2fb1c90dd07f9862b71c789881132193e8f9",
      "edk2_repository_url": "https://github.com/tianocore/edk2.git",
      "edk2_release": "edk2-stable202111",
      "edk2_commit": "bb1bba3d776733c41dbfa2d1dc0fe234819a79f2",
      "binary_version": "03.00.00.0538",
      "os_patch_script": "patch_OS.sh",
      "os_patch": "src/os/patches/0001-Ignore-STATIC_ASSERTs-and-NULL-define-for-os-and-ut-builds.patch",
      "distribution": "Debian",
      "release_major": "13",
      "architecture": "amd64",
      "install_prefix": "/usr/local",
      "allowed_build_types": ["release", "debug"]
    }
  ]
}
