---
debian_release: "trixie"
debian_major_version: 13
debian_components: "main contrib non-free non-free-firmware"
debian_native_python_major_minor: "3.13"
debian_native_python_version_hint: "3.13.5"
controller_python_provider: "system"
controller_python_rebuild_for_legacy: false
controller_python_expected_path: "/usr/bin/python3"
ansible_python_interpreter_controller: "/usr/bin/python3"
ansible_python_interpreter_managed: "/usr/bin/python3"
